# This is a basic workflow to help you get started with Actions

name: Prod - Build and Deploy

# Controls when the action will run. 
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    environment: Prod
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      
      - name: AWS CLI
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Restore dependencies
        run: dotnet restore
    
      - name: Build
        run: dotnet build -c Release --no-restore
      
      - name: Deploy to Lambda
        working-directory: ./src/StaplePuck.Hockey.NHLStatService
        run: dotnet lambda deploy-serverless -sn prod-staplepuck-nhlstats -tp 'Auth0Audience="${{ vars.Auth0__Audience }}";Auth0ClientId="${{ secrets.Auth0__ClientId }}";Auth0ClientSecret="${{ secrets.Auth0__ClientSecret }}";Auth0TokenUrl="${{ vars.Auth0__TokenUrl }}";StaplePuckEndpoint="${{ vars.STAPLEPUNK__ENDPOINT }}";SettingsStatsUrlRoot="${{ vars.NHL_STATSURL }}";SettingsAPIUrlRoot="${{ vars.NHL_APIURL }}"'
